import { RoomFolio } from "../centerdataclass/roomfolio";
import { Chain } from "../centerdataclass/chain";
import { ChainAttachedInfo } from "./chainattachedinfo";
import { AddGuestFolio } from "../frontofficedataclass/addguestFolio";

export class OrderInfo {
    //RoomFolio: RoomFolio;
    //Chain: Chain;
    //AttachedInfo: ChainAttachedInfo;
    //Guests: AddGuestFolio[];
    //GuestName: string;
    //OrderState: number;
    //PayState: number;

    AccState: number;
    ArrAccDate:Date
    Arrival: Date;
    Arrorig: Date;
    ChainAddr: string;
    ChainID: number;
    ChainName: string;
    ChainTel: string;
    ChkOutAccDate: Date;
    ChkOutTime: Date;
    ContactName: string;
    ContractName: string;
    CreateAccDate: Date;
    CreateOprtID: number;
    CreateOprtName: string;
    CreateTime: Date;
    DepAccDate: Date;
    Depart: Date;
    Deporig: Date;
    EMail: string;
    FolioID: number;
    FolioState: number;
    FolioType: number;
    GroupName: string;
    GroupTypeID: number;
    GuestID: number;
    ImageURL: string;
    InnerRemark: string;
    MarketID: number;
    MebID: number;
    MebName: string;
    MebProperty: string;
    MebPropertyTypeID: number;
    MebType: number;
    MebTypeID: number;
    Mobile: string;
    Name: string;
    NightCount: number;
    OrderNo: string;
    PayTransID: number;
    PayTransState: number;
    Phone: string;
    Remark: string;
    RoomCount: number;
    RoomNo: string;
    RoomRate: number;
    RoomRateTypeID: number;
    RoomTypeID: number;
    RoomTypeName: string;
    SellerID: number;
    SellerName: string;
    SourceID: number;
    SourceTypeName: string;
    SubSourceID: number;
    ChineseFolioState: string;
    ChinesePayTransState: string;
    Option: string;
}
