export class FolioPayTrans {
    OriginName: string;
    TargetName: string;
    MebName: string;
    CardNo: string;
    ChainName: string;
    StateName: string;
    PayTransID: number;
    OwnerPayTransID: number;
    OriginID: number;
    OriginTransNo: string;
    TargetTypeID: number;
    MebID: number;
    CreateTime: Date;
    ChainID: number;
    BusKeyID: number;
    Amount: number;
    AccItemCode: number;
    SubAccItemCode: number;
    State: number;
    StateQueryMode: number;
    QueryCount: number;
    MaxQueryCount: number;
    NextQueryTime: Date;
    QueryURL: string;
    NotifyTime: Date;
    ResultCode: string;
    ResultRemark: string;
    TransRemark: string;
    Subject: string;
    NotifyURL: string;
    ReturnURL: string;
    PayMethodType: number
}
